data:
  model_name_or_path: "../pretrainedModel/whisper-chinese"
  train_metadata_path: "../data/processed/train.csv"
  eval_metadata_path: "../data/processed/eval.csv"
  max_train_samples: 0.7 # total percentage from the overal training dataset
  max_eval_samples: 1 # total percentage from overall evaluation dataset.
  audio_column_name: "audio"
  text_column_name: "transcript"
  max_duration_in_seconds: 30.0
  min_duration_in_seconds: 0.0

arch_args:
  freeze_feature_encoder: false
  freeze_encoder: false
  number_layer_freeze_encoder: 12 ## unfreeze top layers in the encoder.
  enable_gradient_checkpoint: true
  apply_spec_augment: true
  mask_time_prob: 0.15
  mask_feature_prob: 0.1
  language: "zh"
  task: "transcribe"
  forced_decoder_ids: null
  supress_tokens: null


train_args:
  train_batch_size: 16
  eval_batch_size: 4
  gradient_accumulation_steps: 2
  output_dir: "../artifacts"
  mixed_precision: true
  log_with: "tensorboard"
  num_warmup_steps: 1000
  num_epochs: 3
  log_steps: 25
  eval_steps: 2000
  save_checkpoint_steps: 2000
  seed: 42
  learning_rate: 0.0001
  tracker: true


audio_augment:
  # re-sampling augmentations
  augment_sr: 8000
  original_sr: 16000

  # speed & pitch augmentation
  speed_factor: [1.8,1.3,1.5,1,1,1,1,0.7,0.9]
  time_stretch_factor: null
  
  # additive_noise
  noise_files: null
  snr_list: [-8, 60] # snr in dbs
  
